config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", sessions: "custom/sessions"  }
  resources :tweets, only: [:index, :show]
  resources :view, only: [:show, :edit]
  
  match 'terms' => 'pages#terms', :via => [:get]

 	match 'new' => 'tweets#index', :via => [:get],  :as => 'user_root'

	devise_scope :user do
	  root to: "custom/sessions#new"
	  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
	end

	match "*path" => redirect("/"), :via => [:get]
end

app/views/view/show.html.erb
<% if current_user %>
<div class="admin-bar">
  <a href="#" class="action left" id="edit">Edit</a>
  <a href="#" class="action left" id="cancel">Cancel</a>
  <%= link_to "Delete", admin_destroy_user_path(@current.uid), :class=>"action left" , method: :delete, data: { confirm: "You sure?" } %>
  <a data-method="delete" href="/users/sign_out" class="action right" id="edit">Logout</a>
  <div class="editable">
    <form id="update-form" action="/view/<%= @current.uid %>/edit" method="GET">
      <div class="theme-option">
        <label for="theme-select">Theme</label>
        <select name="style_id" id="theme-select">
        <% Style.all.each do |style| %>
          <option value="<%= style.style_id %>" data-slug="<%= style.slug %>"><%= style.name %></option>
        <% end %>
        </select>
      </div>
      <div class="theme-option">
        <label for="theme-content">Title</label>
        <input type="text" id="theme-content" name="content" value="<%= @current.title %>">
      </div>
      <input type="submit" value="Save!">
    </form>
  </div>
</div>
<% end %>

<article class="theme <%= @current.style.slug %>">

  <header>
    <div class="inner">
      <h1><%= @current.title %></h1>
      <div class="byline">by <a href="http://twitter.com/<%= @current.uid %>" target="_blank">@<%= @current.uid %></a></div>
    </div>
  </header>

  <% 
  sorted_tweets = @current.tweets.sort_by { |key, value| key["date"] }
  sorted_tweets.each_with_index do |tweet, i| %>
  <% 
  style_id = i+1
  classes = "style-" + style_id.to_s + ' emphasis-' + tweet.importance.to_s 
  %>
  <section class="<%= classes %>">
    <div class="inner">
      <img src="<%= tweet.gif.url %>" alt="<%= tweet.content %>" />
      <div class="date"><%= tweet.date.strftime("%m/%d/%Y") %></div>
      <h2><%= tweet.content %></h2>
    </div>
  </section>
  <% end %>

  <footer>
    <div class="inner">
      The End
      <div class="cta">
        <a href="/">See your year in GIFs</a>
      </div>
      <div class="attribution">
        <a target="_blank" href="http://giphy.com"><%= image_tag 'attribution-' + @current.style.color + '.gif' %></a>
      </div>
    </div>
  </footer>

</article>